config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :diaries
  root 'users#index'
  get "/users/new"
  get "/login", to: "sessions#new"
  post "/login", to:"sessions#create"
  delete "/login", to:"sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord

  validates :title, presence:true, length: {maximum: 255}
  validates :body, presence:true, length: {maximum: 10_000}
  validate :proper_title_and_body

  private

  def proper_title_and_body
    unless title.starts_with?("今日")
      errors.add(:title, "は「今日」から始めてください")
    end
    unless body.ends_with?("。")
      errors.add(:body,"は句点(。)で終了してください")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # 作成したヘルパーメソッドを全てのページで使えるようにする
  # controllerからヘルパーメソッドを呼び出す場合には以下のように明示的に読み込む必要がある
  include SessionsHelper

  private
  # ログイン済みユーザーかどうか確認
  def logged_in_user
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, only: [:show, :edit, :update, :destroy]

  # GET /diaries
  # GET /diaries.json
  def index
    @diaries = Diary.all
  end

  # GET /diaries/1
  # GET /diaries/1.json
  def show
  end

  # GET /diaries/new
  def new
    @diary = Diary.new
  end

  # GET /diaries/1/edit
  def edit
  end

  # POST /diaries
  # POST /diaries.json
  def create
    @diary = Diary.new(diary_params)

    respond_to do |format|
      if @diary.save
        format.html { redirect_to @diary, notice: '投稿完了！' }
        format.json { render :show, status: :created, location: @diary }
      else
        format.html { render :new }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diaries/1
  # PATCH/PUT /diaries/1.json
  def update
    respond_to do |format|
      if @diary.update(diary_params)
        format.html { redirect_to @diary, notice: '更新完了！' }
        format.json { render :show, status: :ok, location: @diary }
      else
        format.html { render :edit }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diaries/1
  # DELETE /diaries/1.json
  def destroy
    @diary.destroy
    respond_to do |format|
      format.html { redirect_to diaries_url, notice: '削除完了！' }
      format.json { head :no_content }
    end
  end

  private
    def set_diary
      @diary = Diary.find(params[:id])
    end

    def diary_params
      params.require(:diary).permit(:title, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  # ログインページから送信された情報を受け取り、ログイン処理を行うアクション
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_url
    else
      render "new"
    end
  end

  # cookieに保存されたユーザーidを削除し、ログアウトを行うアクション
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :logged_in_user, only:[:edit, :update, :destroy]
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index 
    @hello = "hello world"
    # indexを表示したいのでなくてもOK
    # render template: "users/index"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
     # 渡されたユーザーでログインする
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user = @current_user || User.find_by(id: session[:user_id])
      # 上と同じ意味
      # @current_user ||=User.find_by(id: session[:user_id])
    end
  end

  #受け取ったユーザーがログイン中のユーザーと一致すればtrueを返す
  def current_user?(user)
    user == current_user
  end

   # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:userid)
    @current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/diaries/_form.html.erb
<%= form_with(model: diary, local: true) do |form| %>
  <% if diary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(diary.errors.count, "error") %> 保存失敗:</h2>

      <ul>
        <% diary.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :題名 %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :本文 %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit :投稿 %>
  </div>
<% end %>

app/views/diaries/edit.html.erb
<h1>編集</h1>

<%= render 'form', diary: @diary %>

<%= link_to '一覧', @diary %> |
<%= link_to '戻る', diaries_path %>

app/views/diaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>日記一覧</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>登録日時</th>
      <th>更新日時</th>
    </tr>
  </thead>

  <tbody>
    <% @diaries.each do |diary| %>
      <tr>
        <td><%= diary.id %></td>
        <td><%= link_to diary.title, diary %></td>
        <td><%= diary.created_at %></td>
        <td><%= diary.updated_at %></td>
      </tr>
    <% end %> 
  </tbody>
</table>

<br>

<%= link_to '新規登録', new_diary_path %>

app/views/diaries/new.html.erb
<h1>新規登録</h1>

<%= render 'form', diary: @diary %>

<%= link_to 'Back', diaries_path %>

app/views/diaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @diary.id %>
</p>

<p>
  <strong>タイトル:</strong>
  <%= @diary.title %>
</p>

<p>
  <strong>本文:</strong>
  <%= @diary.body %>
</p>

<p>
  <strong>投稿日時:</strong>
  <%= @diary.created_at %>
</p>

<p>
  <strong>更新日時:</strong>
  <%= @diary.updated_at %>
</p>

<%= link_to '編集', edit_diary_path(@diary) %> |
<%= link_to '削除', @diary, method: :delete, data:{confirm:"本当に削除してよろしいですか？"} %>
<%= link_to '戻る', diaries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <%= yield %>
  </body>
</html>

app/views/tasks/_logged_in.html.erb
<h2>タスク一覧</h2>
<table>
  <thead>
    <tr>
      <th>タスク名</th>
    </tr>
  </thead>
</table>
<tbody>
  <% @tasks.earh do |task| %>
    <tr>
      <td><% task.title %></td>
      <td><% link_to "編集", edit_task_path(task) %></td>
      <td><% link_to "削除", task_path(task), method: :delete %></td>
    </tr>
  <% end %>
</tbody>
<% link_to "タスク追加" , new_task_path %>
<% link_to "ログアウト", login_path, method: :delete %>

app/views/tasks/_not_logged_in.html.erb
<p>ログインしてください</p>
<%= link_to "ログイン", login_path %>

app/views/tasks/index.html.erb
<h1>TODO</h1>
<% if logged_in? %>
  <%= render "tasks/logged_in" %>
<% else %>
  <%= render "tasks/not_logged_in" %>
<% end %>

app/views/users/index.html.erb
<div class="users-index"><%=@hello %></div>

app/views/users/new.html.erb
<div>japan</div>